name: CI MAIN

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
      component_name:
        required: false
        type: string
    secrets:
      DTKN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Call from other repo
        uses: actions/checkout@v5

      - name: Display input tag
        run: echo "tag=${{ inputs.tag }}"

      - name: Component name
        run: echo "component name=${{ inputs.component_name }}"

      - name: Check docker
        run: |
          if command -v docker >/dev/null 2>&1; then
            docker --version
          else
            echo "docker not found"
            # fallback install (use Docker repo method if you really need to)
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            docker --version
          fi
          
      - name: Clean old buildx builders
        run: |
          docker buildx ls || true
          docker buildx rm --all-inactive --force || true
          docker ps -a --filter "name=buildx_buildkit" -q | xargs -r docker rm -f
          docker network prune -f || true
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: crysis307
          password: ${{ secrets.DTKN }}

      - name: Set up Docker Buildx (docker-container builder)

        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true


      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: crysis307/${{ inputs.component_name }}:latest,crysis307/${{ inputs.component_name}}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install yq
        run: |
          sudo yum install -y wget
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Update values with new tag
        run: |
          FILE="/tmp/deploy/learn-helm/new helm/env-values-dev/${{ inputs.component_name }}.yaml"
          yq -i '.image.repository = "ghcr.io/your-org/${{ inputs.component_name }}" | .image.tag = "${{ steps.vars.outputs.TAG }}"' "$FILE"
      
      

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: crysis307/${{ inputs.component_name }}:${{ github.sha }}
          output: trivy-results.sarif
          format: "sarif"
          exit-code: '1'   # fail build on critical
          vuln-type: 'os,library'
        env:
          # suppress CLI version check so the action doesn't fail on minor Trivy releases
          TRIVY_SKIP_VERSION_CHECK: 'true'

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

  Dev_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call from other repo
        uses: actions/checkout@v5

      - name: Call from other repo
        run: echo "Dev deploy"

